# Generated by Django 3.0.3 on 2024-10-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensorapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
