# Generated by Django 4.1.13 on 2024-04-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
    ]
