# Generated by Django 5.0.1 on 2024-05-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240421_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.CharField(default='https://icon-library.com/images/anonymous-avatar-icon/anonymous-avatar-icon-25.jpg', max_length=255),
        ),
    ]
