# Generated by Django 4.0.1 on 2024-06-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
