name: Build, Test and Deploy Nova Backend App

on:
  push:
    branches:
      - main
      - test  # Add test branch to trigger workflow

jobs:
  # Build job for both test and main branches
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
           version: v0.7.0

      - name: Build Docker Image
        run: docker build -t nova-backend ./nova_backend

      - name: Tag Docker Image
        run: docker tag nova-backend:latest docker.io/bruno2006/nova-backend:latest

      - name: Docker Login and Push
        run: |
           echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin docker.io
           docker push docker.io/bruno2006/nova-backend:latest

  # Deploy only when on the main branch
  deploy:
    if: github.ref == 'refs/heads/main'  # Only deploy if the branch is main
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create .ssh Directory
        run: mkdir -p $HOME/.ssh
        
      - name: Create known_hosts File
        run: touch $HOME/.ssh/known_hosts

      - name: Remove Old Host Key
        run: ssh-keygen -R ${{ secrets.DEPLOY_HOST }}

      - name: Add and Display Updated Host Key
        run: |
          HOST_KEY=$(ssh-keyscan -t rsa 194.163.167.131)
          echo "$HOST_KEY"
          echo "$HOST_KEY" >> $HOME/.ssh/known_hosts
          
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          # key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          # fingerprint: ${{ secrets.DEPLOY_FINGERPRINT }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin docker.io
            sudo docker pull docker.io/bruno2006/nova-backend
            sudo docker stop nova-backend || true
            sudo docker rm nova-backend || true
            sudo docker run -d --name nova-backend -p 7500:8000 docker.io/bruno2006/nova-backend

  # Add tests job for test branch
  test:
    if: github.ref == 'refs/heads/test'  # Run tests only on the test branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      # Your testing steps
      - name: Run Tests
        run: |
          # Add your test command here, for example:
          docker build -t nova-backend ./nova_backend
          docker run nova-backend pytest  # Replace this with actual test commands

  # Optional job to merge 'test' into 'main' automatically after successful tests
  auto-merge:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test'  # Only merge if it's the 'test' branch
    steps:
      - name: Checkout main branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout main
          git pull origin main

      - name: Merge test into main
        run: |
          git merge test

      - name: Push changes to main
        run: |
          git push origin main
